config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "house#index"
  get '/index', to: 'house#index'
  get '/contact', to: 'house#contact'
  get '/about', to: 'house#about'
  get '/property-grid', to: 'house#property_grid', as: 'search_houses'
  get '/property_single', to: 'house#property_single'
  post '/pages/test', to: 'pages#test'

  resources :houses, controller: 'house' do
    member do
      get 'property_single/:id', to: 'house#property_single', as: 'property_single'
    end
  end

  
  get '/scrape', to: 'pages#scrape'

  resources :users, only: [:new, :create]
  get '/users/login', to: 'users#login', as: 'login'
  post '/users/login', to: 'users#login'
  delete '/logout', to: 'users#logout', as: 'logout'

  post '/property_single/:id/favorite', to: 'house#favorite', as: 'favorite_house'
  delete '/property_single/:id/unfavorite', to: 'house#unfavorite', as: 'unfavorite_house'
  
  get '/users/:id/favourites', to: 'users#favorites', as: 'user_favourites'
  
  get '/users/:id/searches', to: 'users#search', as: 'search'

  post '/property-grid/:id/save_search', to: 'house#save_search', as: 'save_search'
  delete '/property-grid/:id/delete_search', to: 'house#delete_search', as: 'delete_search'

  get '/map_districts', to: 'house#map_districts', as: 'map_districts'

  get '/scripts', to: 'scripts#index'
  post '/scripts/run', to: 'scripts#run_script', as: :run_script
  

  get '/users/index', to: 'users#index', as: 'users_index' 
  patch '/users/update_selected_roles', to: 'users#update_selected_roles', as: 'update_selected_roles_users'




end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :authorize_admin
  def index
    render :dashboard
  end


  def authorize_admin
    unless current_user && current_user.role == 'admin'
      redirect_to root_path, alert: 'Access denied.'
    end
  end

  def run_script
    # Enqueue the script to be executed in the background immediately
    ScriptRunner.new.delay(run_at: 0.seconds.from_now).perform
    # Redirect to the index page to show the user that the script was enqueued
    system('rails jobs:work')
    redirect_to scripts_path
  end

  # Define a separate class to execute the script in the background
  class ScriptRunner < Struct.new(:controller, :args)
    def perform
      # Execute your Python script using the system method

      system("python #{Rails.root}/python/map_districts.py")
      Process.kill('INT', Process.pid)
    end
  end
end
  

app/views/scripts/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>EstateAgency Bootstrap Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <!-- Favicons -->
    <link href="img/favicon.png" rel="icon">
    <link href="img/apple-touch-icon.png" rel="apple-touch-icon">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <!-- Bootstrap CSS File -->
    <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Libraries CSS Files -->
    <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="lib/animate/animate.min.css" rel="stylesheet">
    <link href="lib/ionicons/css/ionicons.min.css" rel="stylesheet">
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <!-- Main Stylesheet File -->
    <link href="css/style.css" rel="stylesheet">
    <!-- =======================================================
    Theme Name: EstateAgency
    Theme URL: https://bootstrapmade.com/real-estate-agency-bootstrap-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
    <style>
      .ui-autocomplete {
        z-index: 9999;
        }
    </style>
  </head>
  <body>
    <div class="click-closed"></div>
    <!--/ Nav Star /-->
    <nav class="navbar navbar-default navbar-trans navbar-expand-lg fixed-top">
      <div class="container">
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault" aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span></span>
          <span></span>
          <span></span>
        </button>
        <a class="navbar-brand text-brand" href="index.html">Invest <span class="color-b">RealEstate</span>
        </a>
        <button type="button" class="btn btn-link nav-search navbar-toggle-box-collapse d-md-none" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-expanded="false">
          <span class="fa fa-search" aria-hidden="true"></span>
        </button>
        <div class="navbar-collapse collapse justify-content-center" id="navbarDefault">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="index.html">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="about.html">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="contact.html">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="map_districts.html">Dados</a>
            </li>
            <li class="nav-item dropdown">
              <li class="nav-item">
                <% if session[:user_id] %>
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Hi <%= User.find(session[:user_id]).name %>!</a>
                <% end %>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/users/<%= session[:user_id] %>/favourites">Favorites</a>
                <a class="dropdown-item" href="/users/<%= session[:user_id] %>/searches">Searches</a>
                <% if current_user && current_user.role == 'admin' %>
                  <a class="dropdown-item" href="/scripts">Update DB</a>
                <% end %>
                 <% if current_user && current_user.role == 'admin' %>
                  <a class="dropdown-item" href="/users/index">Update Users</a>
                <% end %>
                </div>
              </li>
            </li>
            <% if session[:user_id] %>
              <li class="nav-item">
                <%= form_tag logout_path, method: :delete do %>
                  <%= submit_tag "Logout", class: "btn btn-link nav-link" %>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", login_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Register", new_user_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <!--/ Nav End /-->
    <!-- app/views/scripts/index.html.erb -->
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<style>
  .container {
    text-align: center;
  }
</style>

<div class="container">
  <h1>Scripts</h1>

  <!-- Add a form to submit a request to the 'run_script' action -->
  <%= form_tag(run_script_path, method: :post) do %>
    <%= submit_tag 'Run "Update DB"' %>
  <% end %>
</div>


  <!--/ footer Star /-->
  <section class="section-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-4">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">EstateAgency</h3>
            </div>
            <div class="w-body-a">
              <p class="w-text-a color-text-a"> Enim minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip exea commodo consequat duis sed aute irure. </p>
            </div>
            <div class="w-footer-a">
              <ul class="list-unstyled">
                <li class="color-a">
                  <span class="color-text-a">Phone .</span> contact@example.com
                </li>
                <li class="color-a">
                  <span class="color-text-a">Email .</span> +54 356 945234
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">The Company</h3>
            </div>
            <div class="w-body-a">
              <div class="w-body-a">
                <ul class="list-unstyled">
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i>
                    <a href="#">Site Map</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i>
                    <a href="#">Legal</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i>
                    <a href="#">Agent Admin</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i>
                    <a href="#">Careers</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i>
                    <a href="#">Affiliate</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i>
                    <a href="#">Privacy Policy</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">International sites</h3>
            </div>
            <div class="w-body-a">
              <ul class="list-unstyled">
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i>
                  <a href="#">Venezuela</a>
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i>
                  <a href="#">China</a>
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i>
                  <a href="#">Hong Kong</a>
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i>
                  <a href="#">Argentina</a>
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i>
                  <a href="#">Singapore</a>
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i>
                  <a href="#">Philippines</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="nav-footer">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="#">Home</a>
              </li>
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Property</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Blog</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
            </ul>
          </nav>
          <div class="socials-a">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-facebook" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-twitter" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-instagram" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-pinterest-p" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-dribbble" aria-hidden="true"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="copyright-footer">
            <p class="copyright color-text-a"> &copy; Copyright <span class="color-a">EstateAgency</span> All Rights Reserved. </p>
          </div>
          <div class="credits">
            <!--
              All the links in the footer should remain intact.
              You can delete the links only if you purchased the pro version.
              Licensing information: https://bootstrapmade.com/license/
              Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=EstateAgency
            --> Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!--/ Footer End /-->
  <a href="#" class="back-to-top">
    <i class="fa fa-chevron-up"></i>
  </a>
  <!-- JavaScript Libraries -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script src="lib/jquery/jquery-migrate.min.js"></script>
  <script src="lib/popper/popper.min.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script src="lib/easing/easing.min.js"></script>
  <script src="lib/owlcarousel/owl.carousel.min.js"></script>
  <script src="lib/scrollreveal/scrollreveal.min.js"></script>
  <!-- Contact Form JavaScript File -->
  <script src="contactform/contactform.js"></script>
  <!-- Template Main Javascript File -->
  <script src="js/main.js"></script>
  <script>
    $('#advanced-options').hide();
    // toggle advanced options
    $('#adv-search-btn').click(function() {
      $('#advanced-options').slideToggle("fast");
    });
    $('#adv-filter li').click(function() {
      $('#adv-filter li.active').removeClass('active');
      $(this).addClass('active');
    });
  </script>
</body>
</html>