config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "house#index"
  get '/index', to: 'house#index'
  get '/contact', to: 'house#contact'
  get '/about', to: 'house#about'
  get '/property-grid', to: 'house#property_grid', as: 'search_houses'
  get '/property_single', to: 'house#property_single'
  post '/pages/test', to: 'pages#test'

  resources :houses, controller: 'house' do
    member do
      get 'property_single/:id', to: 'house#property_single', as: 'property_single'
    end
  end

  
  get '/scrape', to: 'pages#scrape'

  resources :users, only: [:new, :create]
  get '/users/login', to: 'users#login', as: 'login'
  post '/users/login', to: 'users#login'
  delete '/logout', to: 'users#logout', as: 'logout'

  post '/property_single/:id/favorite', to: 'house#favorite', as: 'favorite_house'
  delete '/property_single/:id/unfavorite', to: 'house#unfavorite', as: 'unfavorite_house'
  
  get '/users/:id/favourites', to: 'users#favorites', as: 'user_favourites'
  
  get '/users/:id/searches', to: 'users#search', as: 'search'

  post '/property-grid/:id/save_search', to: 'house#save_search', as: 'save_search'
  delete '/property-grid/:id/delete_search', to: 'house#delete_search', as: 'delete_search'

  get '/map_districts', to: 'house#map_districts', as: 'map_districts'

  get '/scripts', to: 'scripts#index'
  post '/scripts/run', to: 'scripts#run_script', as: :run_script
  

  get '/users/index', to: 'users#index', as: 'users_index' 
  patch '/users/update_selected_roles', to: 'users#update_selected_roles', as: 'update_selected_roles_users'




end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, uniqueness: true
    has_many :favorites
    has_many :favorite_houses, through: :favorites, source: :house
    has_many :searches, class_name: 'Search', dependent: :destroy

  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController

  
  
  helper_method :sort_column, :sort_direction
  def favorites
    if current_user && current_user.id == params[:id].to_i
      @favorites = current_user.favorite_houses.paginate(page: params[:page], per_page: 9).order(sort_column + " " + sort_direction)
      @image_urls = PagesController.new.scrape(@favorites)
      @houses_map = current_user.favorite_houses
      render "favourites"
    else
      redirect_to root_path, alert: "You are not authorized to view this page"
    end
  end

  def search
    if current_user
      @saved_searches = current_user.searches
    else
      redirect_to root_path, alert: "You need to sign in or sign up before continuing."
    end
  end
  
  

  def new
      @user = User.new
  end

  def login
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to index_path, notice: "Logged in!"
      else
        flash.now.alert = "Email or password is invalid"
        render "login"
      end
  end
    
  def logout
    session[:user_id] = nil
    redirect_to index_url, notice: "Logged out!"
  end
  
  def require_login
    unless session[:user_id]
      redirect_to login_path, alert: "You must be logged in to access this page"
    end
  end

  def create
    @user = User.new(user_params)
    @user.role = 'cliente'
    if @user.save
      session[:user_id] = @user.id
      redirect_to index_path, notice: "Thanks for signing up!"
    else
      render :new
    end
  end
  
  before_action :require_admin, only: [:index, :update_selected_roles]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def update_selected_roles
    selected_user_ids = params[:selected_users]
    new_role = params[:role]
  
    if selected_user_ids.present?
      # Check if any of the selected users are admins
      if User.where(id: selected_user_ids, role: 'admin').exists? || (selected_user_ids.include?(current_user.id.to_s) && new_role == 'cliente')
        redirect_to users_index_path, alert: "Cannot demote an admin user or yourself."
        return
      end
  
      User.where(id: selected_user_ids).update_all(role: new_role)
      redirect_to users_index_path, notice: "Roles updated successfully."
    else
      redirect_to users_index_path, alert: "No users selected."
    end
  end

  private

  def require_admin
    unless current_user && current_user.role == 'admin'
      redirect_to root_path, alert: "Access denied."
    end
  end

    
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def sort_column
    puts "params[:sort]: #{params[:sort_column]}"
    House.column_names.include?(params[:sort_column]) ? params[:sort_column] : "Id"
  end
  
  def sort_direction
    puts "params[:direction]: #{params[:sort_direction]}"
    %w[asc desc].include?(params[:sort_direction]) ? params[:sort_direction] : "asc"
  end
      
  end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/login.html.erb
<link rel="stylesheet" href="/css/login.css">

<div class="login-page">
  <div class="form">
    <%= form_with url: login_path, local: true, html: {class: "login-form"} do |f| %>
      <% if flash[:error] %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>

      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

      <div class="field">
        <%= f.email_field :email, class: "input-field", placeholder: "username", autofocus: true %>
      </div>

      <div class="field">
        <%= f.password_field :password, class: "input-field", placeholder: "password" %>
      </div>

      <button type="submit">
        Log In
      </button>


    <% end %>

    <p class="message">Not registered? <a href="/users/new">Create an account</a></p>
  </div>
</div>

app/views/users/new.html.erb
<link rel="stylesheet" href="/css/login.css">

<div class="login-page">
<div class="form">
  <%= form_with model: @user, url: users_path, method: :post, html: { class: "login-form" } do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.text_field :name, class: "input-field", placeholder: "name" %>
    </div>

    <div class="field">
      <%= f.text_field :email, class: "input-field", placeholder: "email" %>
    </div>

   <div class="field">
      <%= f.password_field :password, class: "input-field", placeholder: "password" %>
    </div>
  
    <div class="field">
      <%= f.password_field :password_confirmation, class: "input-field", placeholder: "password_confirmation" %>
    </div>

    <button type="submit">
        Create
    </button>
  <% end %>
      <p class="message">Already registered? <a href="/users/login">Sign In</a></p>
  </div>
</div>