config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "house#index"
  get '/index', to: 'house#index'
  get '/contact', to: 'house#contact'
  get '/about', to: 'house#about'
  get '/property-grid', to: 'house#property_grid', as: 'search_houses'
  get '/property_single', to: 'house#property_single'
  post '/pages/test', to: 'pages#test'

  resources :houses, controller: 'house' do
    member do
      get 'property_single/:id', to: 'house#property_single', as: 'property_single'
    end
  end

  
  get '/scrape', to: 'pages#scrape'

  resources :users, only: [:new, :create]
  get '/users/login', to: 'users#login', as: 'login'
  post '/users/login', to: 'users#login'
  delete '/logout', to: 'users#logout', as: 'logout'

  post '/property_single/:id/favorite', to: 'house#favorite', as: 'favorite_house'
  delete '/property_single/:id/unfavorite', to: 'house#unfavorite', as: 'unfavorite_house'
  
  get '/users/:id/favourites', to: 'users#favorites', as: 'user_favourites'
  
  get '/users/:id/searches', to: 'users#search', as: 'search'

  post '/property-grid/:id/save_search', to: 'house#save_search', as: 'save_search'
  delete '/property-grid/:id/delete_search', to: 'house#delete_search', as: 'delete_search'

  get '/map_districts', to: 'house#map_districts', as: 'map_districts'

  get '/scripts', to: 'scripts#index'
  post '/scripts/run', to: 'scripts#run_script', as: :run_script
  

  get '/users/index', to: 'users#index', as: 'users_index' 
  patch '/users/update_selected_roles', to: 'users#update_selected_roles', as: 'update_selected_roles_users'




end

app/models/house.rb
class House < ApplicationRecord
    self.primary_key = 'Id'
    has_many :favorites, foreign_key: 'house_id'
    has_many :users_who_favorited, through: :favorites, source: :user
end

app/controllers/house_controller.rb
require 'will_paginate/array'

class HouseController < ApplicationController
  include CurrentUserConcern

    def index
        render :index
    end

    def contact
        render :contact
    end

    def property
        render :'property-grid'
    end

    def about
      render :about
    end

  def map_districts
    if File.exist?('values_places.json')
      file = File.open('values_places.json', 'r')
      results = JSON.parse(file.read)
      file.close
      render :map_districts, locals: { results: results }
      return
    end
  end
    
    helper_method :sort_column, :sort_direction
    def test
        @houses = House.order(sort_column + " " + sort_direction).paginate(page: params[:page], per_page: 10)
    end

    def favorite
      @house = House.find(params[:id])
      current_user.favorite_houses << @house
      redirect_to request.referrer, notice: "House added to favorites."
    end
    
    def unfavorite
      @house = House.find(params[:id])
      current_user.favorite_houses.delete(@house)
      redirect_to request.referrer, notice: "House removed from favorites!"
    end
    
    
    def calculate_area_price
      if(!@house.Price_per_Area.present?)
        if(@house.Price.present? && @house.Area_Bruta.present?)
          @price_per_Area = @house.Price/@house.Area_Bruta.to_d
        elsif (@house.Price.present? && @house.Area_Util.present?)
          @price_per_Area = @house.Price/@house.Area_Util.to_d
        end
        if(@price_per_Area.present?)
          @price_per_Area=@price_per_Area.round(2)
        end
      else
        @price_per_Area = @house.Price_per_Area
      end
    end
    
    def property_single
      id = params[:format]
      @house = House.find(id)    
      puts @house.inspect
      @image_urls = PagesController.new.scrape_single(@house)
      
      calculate_area_price


      localization = @house.Localizacao
      parts = localization.split(',').map(&:strip).reverse
      distrito = parts[0]
      concelho = parts[1]
      freguesia = parts[2]
      
      if distrito.nil?
        @averages_comprar_distrito = nil
      else
        average_price = House.where(situacao: 'comprar').where("Localizacao LIKE ?", "%#{distrito}%").average(:Price)
        @averages_comprar_distrito = average_price.nil? ? nil : average_price.round(2)
      end
      
      if concelho.nil?
        @averages_comprar_concelho = nil
      else
        average_price = House.where(situacao: 'comprar').where("Localizacao LIKE ?", "%#{concelho}%").average(:Price)
        @averages_comprar_concelho = average_price.nil? ? nil : average_price.round(2)
      end
      
      if freguesia.nil?
        @averages_comprar_freguesia = nil
      else
        average_price = House.where(situacao: 'comprar').where("Localizacao LIKE ?", "%#{freguesia}%").average(:Price)
        @averages_comprar_freguesia = average_price.nil? ? nil : average_price.round(2)
      end
      

      if distrito.nil?
        @averages_alugar_distrito = nil
      else
        average_price = House.where(situacao: 'alugar').where("Localizacao LIKE ?", "%#{distrito}%").average(:Price)
        @averages_alugar_distrito = average_price.nil? ? nil : average_price.round(2)
      end
      
      if concelho.nil?
        @averages_alugar_concelho = nil
      else
        average_price = House.where(situacao: 'alugar').where("Localizacao LIKE ?", "%#{concelho}%").average(:Price)
        @averages_alugar_concelho = average_price.nil? ? nil : average_price.round(2)
      end
      
      if freguesia.nil?
        @averages_alugar_freguesia = nil
      else
        average_price = House.where(situacao: 'alugar').where("Localizacao LIKE ?", "%#{freguesia}%").average(:Price)
        @averages_alugar_freguesia = average_price.nil? ? nil : average_price.round(2)
      end
        
    end
    

    
    helper_method :sort_column, :sort_direction
    def property_grid
      query_params = {}
      query_params[:Situacao] = params[:situacao] if params[:situacao].present?
      query_params[:Type] = params[:type] if params[:type].present?
      query_params[:Total_quartos] = params[:Total_quartos] if params[:Total_quartos].present?
      query_params[:Condicao] = params[:Condicao] if params[:Condicao].present?
      query_params[:Acesso_Mobilidade_Reduzida] = params[:Acesso_Mobilidade_Reduzida] if params[:Acesso_Mobilidade_Reduzida].present?
      query_params[:Arrecadação] = params[:Arrecadação] if params[:Arrecadação].present?
      query_params[:Elevador] = params[:Elevador] if params[:Elevador].present?
      query_params[:Garagem] = params[:Garagem] if params[:Garagem].present?
      query_params[:Estacionamento] = params[:Estacionamento] if params[:Estacionamento].present?
      query_params[:Jardim] = params[:Jardim] if params[:Jardim].present?
      query_params[:Lareira] = params[:Lareira] if params[:Lareira].present?
      query_params[:Recuperador_de_calor] = params[:Recuperador_de_calor] if params[:Recuperador_de_calor].present?
      query_params[:Vidros_duplos] = params[:Vidros_duplos] if params[:Vidros_duplos].present?
      query_params[:Varanda] = params[:Varanda] if params[:Varanda].present?
      query_params[:Terraço] = params[:Terraço] if params[:Terraço].present?
      query_params[:Suite] = params[:Suite] if params[:Suite].present?
      query_params[:Segurança] = params[:Segurança] if params[:Segurança].present?
      query_params[:Piscina] = params[:Piscina] if params[:Piscina].present?
      query_params[:Painéis_Solares] = params[:Painéis_Solares] if params[:Painéis_Solares].present?
      query_params[:Mobília] = params[:Mobília] if params[:Mobília].present?
      query_params[:Logradouro] = params[:Logradouro] if params[:Logradouro].present?
      query_params_1 = {}
      query_params_1[:Total_quartos] = params[:Total_quartos] if params[:Total_quartos].present?
      query_params_1[:Condicao] = params[:Condicao] if params[:Condicao].present?
      query_params_1[:Acesso_Mobilidade_Reduzida] = params[:Acesso_Mobilidade_Reduzida] if params[:Acesso_Mobilidade_Reduzida].present?
      query_params_1[:Arrecadação] = params[:Arrecadação] if params[:Arrecadação].present?
      query_params_1[:Elevador] = params[:Elevador] if params[:Elevador].present?
      query_params_1[:Garagem] = params[:Garagem] if params[:Garagem].present?
      query_params_1[:Estacionamento] = params[:Estacionamento] if params[:Estacionamento].present?
      query_params_1[:Jardim] = params[:Jardim] if params[:Jardim].present?
      query_params_1[:Lareira] = params[:Lareira] if params[:Lareira].present?
      query_params_1[:Recuperador_de_calor] = params[:Recuperador_de_calor] if params[:Recuperador_de_calor].present?
      query_params_1[:Vidros_duplos] = params[:Vidros_duplos] if params[:Vidros_duplos].present?
      query_params_1[:Varanda] = params[:Varanda] if params[:Varanda].present?
      query_params_1[:Terraço] = params[:Terraço] if params[:Terraço].present?
      query_params_1[:Suite] = params[:Suite] if params[:Suite].present?
      query_params_1[:Segurança] = params[:Segurança] if params[:Segurança].present?
      query_params_1[:Piscina] = params[:Piscina] if params[:Piscina].present?
      query_params_1[:Painéis_Solares] = params[:Painéis_Solares] if params[:Painéis_Solares].present?
      query_params_1[:Mobília] = params[:Mobília] if params[:Mobília].present?
      query_params_1[:Logradouro] = params[:Logradouro] if params[:Logradouro].present?
      has_price = false
      has_year = false
      
      if params[:min_price].present? && params[:max_price].present?
        min_price = params[:min_price].to_i
        max_price = params[:max_price].to_i
        has_price = true
      elsif params[:min_price].present? && !params[:max_price].present?
        max_price = 9999999999
        min_price = params[:min_price].to_i
        has_price = true
      elsif !params[:min_price].present? && params[:max_price].present?
        min_price = 0
        max_price = params[:max_price].to_i
        has_price = true
      end
      
      if(has_price == true)
        if min_price < max_price
          query_params[:'Price'] = (min_price..max_price)
        else
          params[:min_price] = max_price
          params[:max_price] = min_price
          query_params[:'Price'] = (min_price..max_price)
        end
      end
      if params[:min_year].present? && params[:max_year].present?
        min_year = params[:min_year].to_i
        max_year = params[:max_year].to_i
        has_year = true
      elsif params[:min_year].present? && !params[:max_year].present?
        max_year = 9999999999
        min_year = params[:min_year].to_i
        has_year = true
      elsif !params[:min_year].present? && params[:max_year].present?
        min_year = 0
        max_year = params[:max_year].to_i
        has_year = true
      end
      if(has_year == true)
        if min_year < max_year
          query_params[:Ano_de_Construcao] = (min_year..max_year)
        else
          params[:min_year] = max_year
          params[:max_year] = max_year
          query_params[:Ano_de_Contrucao] = (min_year..max_year)
        end
      end
    if params[:search].present?
      @houses = House.where(query_params).where("Localizacao LIKE ?", "%#{params[:search]}%")
                     .order(sort_column + " " + sort_direction)
                     .paginate(page: params[:page], per_page: 9)
      @houses_map = House.where(query_params).where("Localizacao LIKE ?", "%#{params[:search]}%")
    elsif query_params_1.present? # added check for presence of query parameters
      @houses = House.where(query_params)
                     .order(sort_column + " " + sort_direction)
                     .paginate(page: params[:page], per_page: 9)
      @houses_map = House.where(query_params)
    else # handle case where no query parameters are present
      @houses = House.none.paginate(page: params[:page], per_page: 9)
      @houses_map = []
    end

app/helpers/house_helper.rb
module HouseHelper
end

app/views/house/search.html.erb
  <%= form_tag search_houses_path, method: :get, autocomplete: "off" do %>
    <%= text_field_tag :search, params[:search], id: "search", spellcheck: false, placeholder: "Search by localizacao", data: { source: search_suggestions_path } %>
    <%= select_tag :situacao, options_for_select([['For Rent', 'alugar'], ['For Sale', 'comprar']], params[:situacao]), include_blank: false %>
    <%= select_tag :type, options_for_select([['Moradia', 'moradias'], ['Apartamento', 'apartamentos']], params[:type]), include_blank: false %>  

    <%= check_box_tag 'Condicao[]', 'Novo', params[:Condicao]&.include?('Novo') %> Novo
    <%= check_box_tag 'Condicao[]', 'Usado', params[:Condicao]&.include?('Usado') %> Usado
    <%= check_box_tag 'Condicao[]', 'Recuperado', params[:Condicao]&.include?('Recuperado') %> Recuperado
    <%= check_box_tag 'Condicao[]', 'Por recuperar', params[:Condicao]&.include?('Por recuperar') %> Por recuperar

    <%= check_box_tag 'Total_quartos[]', '0', params[:Total_quartos]&.include?('0') %> T0
    <%= check_box_tag 'Total_quartos[]', '1', params[:Total_quartos]&.include?('1') %> T1
    <%= check_box_tag 'Total_quartos[]', '2', params[:Total_quartos]&.include?('2') %> T2
    <%= check_box_tag 'Total_quartos[]', '3', params[:Total_quartos]&.include?('3') %> T3
    <%= check_box_tag 'Total_quartos[]', '4', params[:Total_quartos]&.include?('4') %> T4
    <%= check_box_tag 'Total_quartos[]', '5', params[:Total_quartos]&.include?('5') %> T5
    <%= check_box_tag 'Total_quartos[]', '6', params[:Total_quartos]&.include?('6') %> T6

    <%= text_field_tag :min_price, params[:min_price], placeholder: "Minimum Price"%>
    <%= text_field_tag :max_price, params[:max_price], placeholder: "Maximum Price"%>

    <%= text_field_tag :min_year, params[:min_year], placeholder: "Minimum Year"%>
    <%= text_field_tag :max_year, params[:max_year], placeholder: "Maximum Year"%>
    <br>Acesso_Mobilidade_Reduzida
    <%= select_tag :Acesso_Mobilidade_Reduzida, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Acesso_Mobilidade_Reduzida]), include_blank: true %>
    <br>Arrecadação
    <%= select_tag :Arrecadação, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Arrecadação]), include_blank: true %>
    <br>Elevador
    <%= select_tag :Elevador, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Elevador]), include_blank: true %>
    <br>Garagem
    <%= select_tag :Garagem, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Garagem]), include_blank: true %>
    <br>Estacionamento
    <%= select_tag :Estacionamento, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Estacionamento]), include_blank: true %>
    <br>Jardim
    <%= select_tag :Jardim, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Jardim]), include_blank: true %>
    <br>Lareira
    <%= select_tag :Lareira, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Lareira]), include_blank: true %>
    <br>Recuperador_de_calor
    <%= select_tag :Recuperador_de_calor, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Recuperador_de_calor]), include_blank: true %>
    <br>Vidros_duplos
    <%= select_tag :Vidros_duplos, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Vidros_duplos]), include_blank: true %>
    <br>Varanda
    <%= select_tag :Varanda, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Varanda]), include_blank: true %>
    <br>Terraço
    <%= select_tag :Terraço, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Terraço]), include_blank: true %>
    <br>Suite
    <%= select_tag :Suite, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Suite]), include_blank: true %>
    <br>Segurança
    <%= select_tag :Segurança, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Segurança]), include_blank: true %>
    <br>Piscina
    <%= select_tag :Piscina, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Piscina]), include_blank: true %>
    <br>Painéis_Solares
    <%= select_tag :Painéis_Solares, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Painéis_Solares]), include_blank: true %>
    <br>Logradouro
    <%= select_tag :Logradouro, options_for_select([['Sim', 'TRUE'], ['Nao', 'FALSE']], params[:Logradouro]), include_blank: true %>


    <%= submit_tag "Search" %>
 
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <%= javascript_include_tag 'search' %>
 <% end %>

  <% if @houses.any? %>
    <table>
      <thead>
        <tr>
          <th><%= sortable "Id" %></th>
          <th><%= sortable "Title" %></th>
          <th>Localizacao</th>
          <th>Situacao</th>
          <th>Type</th>
          <th><%= sortable "Price"%></th>
          <th>Condicao</th>
          <th>Numero Quartos</th>
          <th>Ano</th>
          <th>Mobilidade Reduzida</th>
        </tr>
      </thead>
      <tbody>
        <% @houses.each do |house| %>
          <tr>
            <td><%= house.Id %></td>
            <td><a href = "<%= house.Url %>"><%= house.Title %></a></td>
            <td><%= house.Localizacao %></td>
            <td><%= house.Situacao %></td>
            <td><%= house.Type %></td>
            <td><%= house.Price %></td>
            <td><%= house.Condicao %></td>
            <td><%= house.Total_quartos %></td>
            <td><%= house.Ano_de_Construcao %></td>
            <td><%= house.Acesso_Mobilidade_Reduzida %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No results found.</p>
  <% end %>
  <%= will_paginate @houses %>
  <style>
    #map {
      width: 100%;
      height: 600px;
    }
  </style>
  <div id="map"></div>
  <%= javascript_include_tag 'leaflet' %>
  <%= javascript_include_tag 'leaflet.draw' %>
  <%= javascript_include_tag 'populate_selectedmarkers' %>
  <table id="selected-markers-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Location</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  
  <script>
    var houseMarkers = [<% @houses_map.select{ |house| house.Latitude.present? && house.Longitude.present? }.each do |house| %>      { Latitude: <%= house.Latitude %>, Longitude: <%= house.Longitude %>, Title: '<%= house.Title %>', Url:  '<%= house.Url %>', Price:  '<%= house.Price %>', Localizacao:  '<%= house.Localizacao %>'},    <% end %>  ];

    var mymap = L.map('map').setView([38.736946, -9.142685], 6);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
      maxZoom: 18
    }).addTo(mymap);

    for (var i = 0; i < houseMarkers.length; i++) {
      var marker = L.marker([houseMarkers[i].Latitude, houseMarkers[i].Longitude], {
        icon: L.icon({
          iconUrl: '/img/marker-icon.png',
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [0, -35]
        })
      });

      var popupContent = "";
      for (var j = 0; j < houseMarkers.length; j++) {
        if (houseMarkers[j].Latitude == houseMarkers[i].Latitude &&
            houseMarkers[j].Longitude == houseMarkers[i].Longitude) {
          popupContent += "<a href='" + houseMarkers[j].Url + "'>" + houseMarkers[j].Title + "</a>";
        }
      }

      marker.bindPopup(popupContent).addTo(mymap);
    }

    var drawnItems = new L.FeatureGroup();
    mymap.addLayer(drawnItems);

    var drawControl = new L.Control.Draw({
      edit: {
          featureGroup: drawnItems
      },
      draw: {
          polyline: false,
          polygon: true,
          rectangle: true,
          marker: false,
          circlemarker: false,
          circle: false
      }
    });


    mymap.addControl(drawControl);

    mymap.on(L.Draw.Event.CREATED, function(event) {
      var layer = event.layer;
      drawnItems.addLayer(layer);

      var bounds = layer.getBounds();
      var selectedMarkers = houseMarkers.filter(function(marker) {
        var latlng = L.latLng(marker.Latitude, marker.Longitude);
        return bounds.contains(latlng);
      });

      var popupContent = "";
      for (var i = 0; i < selectedMarkers.length; i++) {
        popupContent += "<a href='" + selectedMarkers[i].Url + "'>" + selectedMarkers[i].Title + "</a><br>";
      }

      L.popup()
        .setLatLng(bounds.getCenter())
        .setContent(popupContent)
        .openOn(mymap);

      mymap.on('draw:deleted', function () {
        drawnItems.clearLayers();
        document.getElementById("selected-markers-table").getElementsByTagName("tbody")[0].innerHTML = "";
      });

      populateSelectedMarkersTable(selectedMarkers);
    });
  </script>